routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//------------------------------------- Overriding Auth Routes ---------------------------------------------------------
Auth::routes();

// Authentication Routes...
Route::get('login', [
    'as' => 'login',
    'uses' => 'Auth\LoginController@showLoginForm'
]);
Route::post('login', [
    'as' => '',
    'uses' => 'Auth\LoginController@login'
]);
Route::post('logout', [
    'as' => 'logout',
    'uses' => 'Auth\LoginController@logout'
]);

// Password Reset Routes...
Route::post('password/email', [
    'as' => 'password.email',
    'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail'
]);
Route::get('password/reset', [
    'as' => 'password.request',
    'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm'
]);
Route::post('password/reset', [
    'as' => '',
    'uses' => 'Auth\ResetPasswordController@reset'
]);
Route::get('password/reset/{token}', [
    'as' => 'password.reset',
    'uses' => 'Auth\ResetPasswordController@showResetForm'
]);

// Registration Routes...
Route::get('signupvugichugiblabla741852963', [
    'as' => 'signupvugichugiblabla654321',
    'uses' => 'Auth\RegisterController@showRegistrationForm'
]);
Route::post('signupvugichugiblabla654321', [
    'as' => '',
    'uses' => 'Auth\RegisterController@register'
]);

Route::get('/home', 'HomeController@index')->name('home');



Route::get('/', 'Auth\LoginController@showLoginForm');

Route::group(['middleware' => ['auth:web']], function() {
    Route::get('dashboard', 'DashboardController@index');
    Route::get('foodprice', 'FoodOrdersController@fetchFoodPrice');

    Route::resources([
        'staff'                   => 'StaffController',
        'salary-transaction'      => 'SalaryTransactionsController',
        'inventory'               => 'InventoryController',
        'inventory-orders'        => 'InventoryOrderController',
        'raw-materials'           => 'RawMaterialsController',
        'vendors'                 => 'VendorsController',
        'food-order-types'        => 'FoodOrderTypesController',
        'food-orders'             => 'FoodOrdersController',
        'food-menu-categories'    => 'FoodMenuCategoriesController',
        'food-menu'               => 'FoodMenuController',
        'cashbox'                 => 'CashBoxController',
        'cashbox-trnx'            => 'CashBoxTrnxController',
        'cashbox-trnx-categories' => 'CashBoxTrnxCategriesController'
    ]);
});

app/Inventory.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Inventory extends Model
{
    use SoftDeletes;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'inventory';

    /**
     * The Primary id associated with the table.
     *
     * @var string
     */
    protected $primaryKey = 'inv_id';

    /**
     * Get Staff joining date.
     *
     * @param  string  $value
     * @return string
     */
    public function getInvDateAttribute($date)
    {
        return $date ? Carbon::createFromFormat('Y-m-d', $date)->format('j F, Y') : '';
    }

    /**
     * Get the Raw Materials that owns the Inventory.
     */
    public function rawMaterial()
    {
        return $this->belongsTo('App\RawMaterial', 'rm_id', 'rm_id');
    }
}

app/InventoryOrderMaster.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class InventoryOrderMaster extends Model
{
    use SoftDeletes;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'inventoryordermaster';

    /**
     * The Primary id associated with the table.
     *
     * @var string
     */
    protected $primaryKey = 'iom_id';

    /**
     * Get Staff Inventory Order Date.
     *
     * @param  string  $value
     * @return string
     */
    public function getIomDateAttribute($date)
    {
        return $date ? Carbon::createFromFormat('Y-m-d', $date)->format('j F, Y') : '';
    }

    /**
     * Get the Inventory Order Details for the Inventory Order Master.
     */
    public function details()
    {
        return $this->hasMany('App\InventoryOrderDetails', 'iom_id', 'iom_id');
    }

    /**
     * Get the vendor that owns the Inventory Order Master.
     */
    public function vendor()
    {
        return $this->belongsTo('App\Vendor', 'v_id', 'v_id');
    }

    /**
     * Get the Ordered user that owns the Inventory Order Master.
     */
    public function orderedUser()
    {
        return $this->belongsTo('App\User', 'iom_orderedUserId', 'u_id');
    }

    /**
     * Get the Received user that owns the Inventory Order Master.
     */
    public function receivedUser()
    {
        return $this->belongsTo('App\User', 'iom_receivedUserId', 'u_id');
    }
}

app/Http/Controllers/InventoryController.php
<?php

namespace App\Http\Controllers;

use App\Inventory;
use Carbon\Carbon;
use Illuminate\Http\Request;

class InventoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['menu'] = 'inventory';
        $data['inventory'] = Inventory::where('inv_date', Carbon::today()->toDateString())
            ->get();

        return view('inventory.status', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/inventory/orders.add.blade.php
@extends('layouts.master')

@section('title', 'Add New Staff')

@section('customcss')
    <link href="{{asset('public/assets/vendors/custom/datatables/datatables.bundle.css')}}" rel="stylesheet" type="text/css" />
@endsection

@section('main')
    <div class="m-grid__item m-grid__item--fluid m-wrapper">

        <!-- BEGIN: Subheader -->
        <div class="m-subheader ">
            <div class="d-flex align-items-center">
                <div class="mr-auto">
                    <h3 class="m-subheader__title ">New Staff</h3>
                </div>
            </div>
        </div>

        <div class="m-portlet m-portlet--mobile">

            <!--begin::Form-->
            <form class="m-form m-form--fit m-form--label-align-right"
                  action="{{url('staff')}}"
                  method="post"
                  enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="m-portlet__body">
                    <div class="col-sm-12" style="padding-left: 0;">
                        @if (session('success'))
                            <div class="alert alert-success">
                                {{ session('success') }}
                            </div>
                        @elseif($errors->any())
                            <div class="alert alert-danger">
                                {{ $errors->first() }}
                            </div>
                        @endif
                    </div>

                    <div class="form-group m-form__group">
                        <label for="name">Name</label>
                        <input type="text"
                               class="form-control m-input"
                               id="name" value="{{old('name')}}"
                               name="name"
                               aria-describedby="staffName"
                               placeholder="Enter name">
                        <span class="m-form__help">Staff's Full Name</span>
                    </div>

                    <div class="form-group m-form__group">
                        <label for="mobile">Mobile</label>
                        <input type="text"
                               class="form-control m-input"
                               id="mobile"
                               value="{{old('mobile')}}"
                               name="mobile"
                               aria-describedby="staffMobile"
                               placeholder="Enter Mobile No.">
                        <span class="m-form__help">Staff's Contact Number</span>
                    </div>

                    <div class="form-group m-form__group">
                        <label for="address">Address</label>
                        <textarea class="form-control m-input" id="address" name="address" rows="3" placeholder="Enter Address">{{old('address')}}</textarea>
                    </div>

                    <div class="form-group m-form__group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control m-input" id="password" name="password" placeholder="Choose a password for the staff">
                    </div>

                    <div class="form-group m-form__group">
                        <label for="role">Role</label>
                        <select id="role" name="role" class="form-control m-input">
                            @foreach ($userRoles as $userRole):
                            <option value="{{$userRole->ur_id}}">{{$userRole->ur_name}}</option>
                            @endforeach
                        </select>
                        <span class="m-form__help">Choose Staff Role</span>
                    </div>

                    <div class="form-group m-form__group">
                        <label for="image">Image</label>
                        <input type="file" class="form-control m-input" id="image" name="image" aria-describedby="emailHelp">
                        <span class="m-form__help">Staff's Picture</span>
                    </div>

                    <div class="form-group m-form__group">
                        <label for="salary">Salary</label>
                        <input type="text" class="form-control m-input" id="salary" name="salary" value="{{old('salary')}}" aria-describedby="emailHelp" placeholder="Enter Salary">
                        <span class="m-form__help">Staff's Salary you'll provide</span>
                    </div>

                    <div class="form-group m-form__group">
                        <label for="joiningDate">Joining Date</label>
                        <input type="text" class="form-control m-input" id="joiningDate" name="joiningDate" value="{{old('joiningDate')}}" aria-describedby="emailHelp" placeholder="Enter Staff's joining date">
                        <span class="m-form__help">Staff's Joining Date</span>
                    </div>
                </div>

                <div class="m-portlet__foot m-portlet__foot--fit">
                    <div class="m-form__actions">
                        <button type="submit" class="btn btn-primary">Add Staff</button>
                        <button type="reset" class="btn btn-secondary">Cancel</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('customjs')
    <script src="{{asset('public/assets/vendors/custom/datatables/datatables.bundle.js')}}"></script>
    <script src="{{asset('public/js/staff.js')}}"></script>
@endsection

resources/views/inventory/ordersList.blade.php
@extends('layouts.master')

@section('title', 'Inventory Orders')

@section('customcss')
    <link href="{{asset('public/assets/vendors/custom/datatables/datatables.bundle.css')}}" rel="stylesheet" type="text/css" />
@endsection

@section('main')
    <div class="m-grid__item m-grid__item--fluid m-wrapper">

        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Inventory Orders
                        </h3>
                    </div>
                </div>
                <div class="m-portlet__head-tools">
                    <ul class="m-portlet__nav">
                        <li class="m-portlet__nav-item">
                            <a href="{{url('inventiry-orders/create')}}" class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air">
                                <span>
                                    <i class="la la-plus"></i>
                                    <span>Add Inventory Order</span>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="m-portlet__body">

                <!--begin: Datatable -->
                <table class="table table-striped- table-bordered table-hover table-checkable" id="staffList">
                    <thead>
                    <tr>
                        <th>Date</th>
                        <th>Vendor</th>
                        <th>Bill</th>
                        <th>Paid</th>
                        <th>Ordered</th>
                        <th>Received</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($inventoryOrders as $inventoryOrder)
                        <tr data-id="{{$inventoryOrder->iom_id}}">
                            <td>{{$inventoryOrder->iom_date}}</td>
                            <td>{{$inventoryOrder->vendor->v_name}}</td>
                            <td>{{$inventoryOrder->iom_bill}}</td>
                            <td>{{$inventoryOrder->iom_paid}}</td>
                            <td>{{$inventoryOrder->orderedUser->u_name}}</td>
                            <td>{{$inventoryOrder->receivedUser->u_name}}</td>
                            <td>
                                <a href="{{url('inventory-orders/'. $inventoryOrder->iom_id)}}" class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill" title="Details">
                                    <i class="la la-search-plus"></i>
                                </a>

                                <a href="{{url('inventory-orders/'. $inventoryOrder->iom_id . '/edit')}}" class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill" title="Edit">
                                    <i class="la la-edit"></i>
                                </a>

                                <a href="javascript:void(0)" class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill" title="Delete" data-toggle="tooltip"><i class="la la-trash"></i></a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('customjs')
    <script src="{{asset('public/assets/vendors/custom/datatables/datatables.bundle.js')}}" type="text/javascript"></script>
    <script src="{{asset('public/js/staff.js')}}" type="text/javascript"></script>
@endsection

resources/views/inventory/rawMaterials.add.blade.php
@extends('layouts.master')

@section('title', 'Add New Staff')

@section('customcss')
    <link href="{{asset('public/assets/vendors/custom/datatables/datatables.bundle.css')}}" rel="stylesheet" type="text/css" />
@endsection

@section('main')
    <div class="m-grid__item m-grid__item--fluid m-wrapper">

        <!-- BEGIN: Subheader -->
        <div class="m-subheader ">
            <div class="d-flex align-items-center">
                <div class="mr-auto">
                    <h3 class="m-subheader__title ">New Staff</h3>
                </div>
            </div>
        </div>

        <div class="m-portlet m-portlet--mobile">

            <!--begin::Form-->
            <form class="m-form m-form--fit m-form--label-align-right"
                  action="{{url('staff')}}"
                  method="post"
                  enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="m-portlet__body">
                    <div class="col-sm-12" style="padding-left: 0;">
                        @if (session('success'))
                            <div class="alert alert-success">
                                {{ session('success') }}
                            </div>
                        @elseif($errors->any())
                            <div class="alert alert-danger">
                                {{ $errors->first() }}
                            </div>
                        @endif
                    </div>

                    <div class="form-group m-form__group">
                        <label for="name">Name</label>
                        <input type="text"
                               class="form-control m-input"
                               id="name" value="{{old('name')}}"
                               name="name"
                               aria-describedby="staffName"
                               placeholder="Enter name">
                        <span class="m-form__help">Staff's Full Name</span>
                    </div>

                    <div class="form-group m-form__group">
                        <label for="mobile">Mobile</label>
                        <input type="text"
                               class="form-control m-input"
                               id="mobile"
                               value="{{old('mobile')}}"
                               name="mobile"
                               aria-describedby="staffMobile"
                               placeholder="Enter Mobile No.">
                        <span class="m-form__help">Staff's Contact Number</span>
                    </div>

                    <div class="form-group m-form__group">
                        <label for="address">Address</label>
                        <textarea class="form-control m-input" id="address" name="address" rows="3" placeholder="Enter Address">{{old('address')}}</textarea>
                    </div>

                    <div class="form-group m-form__group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control m-input" id="password" name="password" placeholder="Choose a password for the staff">
                    </div>

                    <div class="form-group m-form__group">
                        <label for="role">Role</label>
                        <select id="role" name="role" class="form-control m-input">
                            @foreach ($userRoles as $userRole):
                            <option value="{{$userRole->ur_id}}">{{$userRole->ur_name}}</option>
                            @endforeach
                        </select>
                        <span class="m-form__help">Choose Staff Role</span>
                    </div>

                    <div class="form-group m-form__group">
                        <label for="image">Image</label>
                        <input type="file" class="form-control m-input" id="image" name="image" aria-describedby="emailHelp">
                        <span class="m-form__help">Staff's Picture</span>
                    </div>

                    <div class="form-group m-form__group">
                        <label for="salary">Salary</label>
                        <input type="text" class="form-control m-input" id="salary" name="salary" value="{{old('salary')}}" aria-describedby="emailHelp" placeholder="Enter Salary">
                        <span class="m-form__help">Staff's Salary you'll provide</span>
                    </div>

                    <div class="form-group m-form__group">
                        <label for="joiningDate">Joining Date</label>
                        <input type="text" class="form-control m-input" id="joiningDate" name="joiningDate" value="{{old('joiningDate')}}" aria-describedby="emailHelp" placeholder="Enter Staff's joining date">
                        <span class="m-form__help">Staff's Joining Date</span>
                    </div>
                </div>

                <div class="m-portlet__foot m-portlet__foot--fit">
                    <div class="m-form__actions">
                        <button type="submit" class="btn btn-primary">Add Staff</button>
                        <button type="reset" class="btn btn-secondary">Cancel</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('customjs')
    <script src="{{asset('public/assets/vendors/custom/datatables/datatables.bundle.js')}}"></script>
    <script src="{{asset('public/js/staff.js')}}"></script>
@endsection

resources/views/inventory/rawmaterialsList.blade.php
@extends('layouts.master')

@section('title', 'Raw Materials')

@section('customcss')
    <link href="{{asset('public/assets/vendors/custom/datatables/datatables.bundle.css')}}" rel="stylesheet" type="text/css" />
@endsection

@section('main')
    <div class="m-grid__item m-grid__item--fluid m-wrapper">

        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Raw Materials
                        </h3>
                    </div>
                </div>
                <div class="m-portlet__head-tools">
                    <ul class="m-portlet__nav">
                        <li class="m-portlet__nav-item">
                            <a href="{{url('staff/create')}}" class="btn btn-info m-btn m-btn--custom m-btn--icon m-btn--air">
                                <span>
                                    <i class="la la-plus"></i>
                                    <span>Add New Raw Materials</span>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="m-portlet__body">
                <!--begin: Datatable -->
                <table class="table table-striped- table-bordered table-hover table-checkable" id="rawMaterialList">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th class="text-center">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($rawMaterials as $rawMaterial)
                        <tr data-id="{{$rawMaterial->rm_id}}">
                            <td>{{$rawMaterial->rm_name}}</td>
                            <td>{{$rawMaterial->rm_description}}</td>
                            <td class="text-center">
                                <a href="javascript:void(0)" class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill" title="Details">
                                    <i class="la la-search-plus"></i>
                                </a>

                                <a href="{{url('raw-materials/'. $rawMaterial->rm_id . '/edit')}}" class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill" title="Edit">
                                    <i class="la la-edit"></i>
                                </a>

                                <a href="javascript:void(0)" class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill" title="Delete" data-toggle="tooltip"><i class="la la-trash"></i></a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('customjs')
    <script src="{{asset('public/assets/vendors/custom/datatables/datatables.bundle.js')}}" type="text/javascript"></script>
    <script src="{{asset('public/js/staff.js')}}" type="text/javascript"></script>
@endsection

resources/views/inventory/showOrder.blade.php
@extends('layouts.master')

@section('title', 'Inventory Order')

@section('customcss')

@endsection

@section('main')
    <div class="m-grid__item m-grid__item--fluid m-wrapper">

        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Inventory Order
                        </h3>
                    </div>
                </div>
            </div>
            <div class="m-portlet__body">

                <!--begin: Datatable -->
                <table class="table table-striped- table-bordered table-hover" id="inventory-order">
                    <tr>
                        <th>Date</th>
                        <td>{{$order->iom_date}}</td>
                    </tr>
                    <tr>
                        <th>Vendor</th>
                        <td>{{$order->vendor->v_name}}</td>
                    </tr>
                    <tr>
                        <th>Description</th>
                        <td>{{$order->iom_description}}</td>
                    </tr>
                    <tr>
                        <th>Bill</th>
                        <td>&#2547; {{$order->iom_bill}}</td>
                    </tr>
                    <tr>
                        <th>Paid</th>
                        <td>&#2547; {{$order->iom_paid}}</td>
                    </tr>
                    <tr>
                        <th>Ordered By</th>
                        <td>{{$order->orderedUser->u_name}}</td>
                    </tr>
                    <tr>
                        <th>Received By</th>
                        <td>{{$order->receivedUser->u_name}}</td>
                    </tr>
                </table>

                <br />
                <h4>Order Details</h4>
                <table class="table table-striped- table-bordered table-hover">
                    <thead>
                    <tr>
                        <th>Raw Material</th>
                        <th>Unit Price</th>
                        <th>Ordered Quantity</th>
                        <th>Received Quantity</th>
                        <th>Total Price</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($order->details as $detail):
                    <tr>
                        <td>{{$detail->rawMaterial->rm_name}}</td>
                        <td>&#2547; {{$detail->iod_unitPrice}}</td>
                        <td>{{$detail->iod_orderedQuantity}}</td>
                        <td>{{$detail->iod_receivedQuantity}}</td>
                        <td>&#2547; {{$detail->iod_totalPrice}}</td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('customjs')

@endsection

resources/views/inventory/status.blade.php
@extends('layouts.master')

@section('title', 'Inventory Status')

@section('customcss')
    <link href="{{asset('public/assets/vendors/custom/datatables/datatables.bundle.css')}}" rel="stylesheet" type="text/css" />
@endsection

@section('main')
    <div class="m-grid__item m-grid__item--fluid m-wrapper">

        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            {{$inventory[0]->inv_date}}
                        </h3>
                    </div>
                </div>
            </div>
            <div class="m-portlet__body">

                <!--begin: Datatable -->
                <table class="table table-striped- table-bordered table-hover table-checkable" id="inventoryStatus">
                    <thead>
                    <tr>
                        <th>Raw Material</th>
                        <th>Beginning Quantity</th>
                        <th>Ordered Quantity</th>
                        <th>Received Quantity</th>
                        <th>Present Quantity</th>
                        <th>Ending Quantity</th>
                        <th>Usage</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($inventory as $inv)
                        <tr>
                            <td>{{$inv->rawMaterial->rm_name}}</td>
                            <td>{{$inv->Inv_beginningQty}}</td>
                            <td>{{$inv->Inv_orderedQty}}</td>
                            <td>{{$inv->Inv_rerceivedQty}}</td>
                            <td>{{$inv->inv_presentQty}}</td>
                            <td>{{$inv->inv_endingQty}}</td>
                            <td>{{$inv->inv_usage}}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('customjs')
    <script src="{{asset('public/assets/vendors/custom/datatables/datatables.bundle.js')}}" type="text/javascript"></script>
    <script src="{{asset('public/js/staff.js')}}" type="text/javascript"></script>
@endsection