routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//------------------------------------- Overriding Auth Routes ---------------------------------------------------------
Auth::routes();

// Authentication Routes...
Route::get('login', [
    'as' => 'login',
    'uses' => 'Auth\LoginController@showLoginForm'
]);
Route::post('login', [
    'as' => '',
    'uses' => 'Auth\LoginController@login'
]);
Route::post('logout', [
    'as' => 'logout',
    'uses' => 'Auth\LoginController@logout'
]);

// Password Reset Routes...
Route::post('password/email', [
    'as' => 'password.email',
    'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail'
]);
Route::get('password/reset', [
    'as' => 'password.request',
    'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm'
]);
Route::post('password/reset', [
    'as' => '',
    'uses' => 'Auth\ResetPasswordController@reset'
]);
Route::get('password/reset/{token}', [
    'as' => 'password.reset',
    'uses' => 'Auth\ResetPasswordController@showResetForm'
]);

// Registration Routes...
Route::get('signupvugichugiblabla741852963', [
    'as' => 'signupvugichugiblabla654321',
    'uses' => 'Auth\RegisterController@showRegistrationForm'
]);
Route::post('signupvugichugiblabla654321', [
    'as' => '',
    'uses' => 'Auth\RegisterController@register'
]);

Route::get('/home', 'HomeController@index')->name('home');



Route::get('/', 'Auth\LoginController@showLoginForm');

Route::group(['middleware' => ['auth:web']], function() {
    Route::get('dashboard', 'DashboardController@index');
    Route::get('foodprice', 'FoodOrdersController@fetchFoodPrice');

    Route::resources([
        'staff'                   => 'StaffController',
        'salary-transaction'      => 'SalaryTransactionsController',
        'inventory'               => 'InventoryController',
        'inventory-orders'        => 'InventoryOrderController',
        'raw-materials'           => 'RawMaterialsController',
        'vendors'                 => 'VendorsController',
        'food-order-types'        => 'FoodOrderTypesController',
        'food-orders'             => 'FoodOrdersController',
        'food-menu-categories'    => 'FoodMenuCategoriesController',
        'food-menu'               => 'FoodMenuController',
        'cashbox'                 => 'CashBoxController',
        'cashbox-trnx'            => 'CashBoxTrnxController',
        'cashbox-trnx-categories' => 'CashBoxTrnxCategriesController'
    ]);
});

app/SalaryTransaction.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class SalaryTransaction extends Model
{
    use SoftDeletes;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'salarytransaction';

    /**
     * The Primary id associated with the table.
     *
     * @var string
     */
    protected $primaryKey = 'st_id';

    /**
     * Get Staff Salary Month.
     *
     * @param  string  $value
     * @return string
     */
    public function getStMonthAttribute($date)
    {
        return $date ? Carbon::createFromFormat('Y-m-d', $date)->format('F, Y') : '';
    }

    /**
     * Get Staff Salary Transaction date.
     *
     * @param  string  $value
     * @return string
     */
    public function getCreatedAtAttribute($date)
    {
        return $date ? Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('j F, Y') : '';
    }

    /**
     * Get the staff that owns the Salary Transaction.
     */
    public function staff()
    {
        return $this->belongsTo('App\Staff', 's_id', 's_id');
    }

    /**
     * Get the owner that owns the Salary Transaction.
     */
    public function owner()
    {
        return $this->belongsTo('App\Owner', 'o_id', 'o_id');
    }
}

app/Staff.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Staff extends Model
{
    use SoftDeletes;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'staff';

    /**
     * The Primary id associated with the table.
     *
     * @var string
     */
    protected $primaryKey = 's_id';

    /**
     * Get Staff joining date.
     *
     * @param  string  $value
     * @return string
     */
    public function getSJoiningDateAttribute($date)
    {
        return $date ? Carbon::createFromFormat('Y-m-d', $date)->format('j F, Y') : '';
    }

    /**
     * Get the user that owns the staff.
     */
    public function user()
    {
        return $this->belongsTo('App\User', 'u_id', 'u_id');
    }

    /**
     * Get the Salary Transactions for the staff.
     */
    public function salaryTransaction()
    {
        return $this->hasMany('App\SalaryTransaction', 's_id', 's_id');
    }

    /**
     * Get the Ordered Foods for the Staff.
     */
    public function orderedFoods()
    {
        return $this->hasMany('App\OrderedFoodsMaster', 's_id', 's_id');
    }
}

app/Http/Controllers/StaffController.php
<?php

namespace App\Http\Controllers;

use App\Staff;
use App\User;
use App\UserRole;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class StaffController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['menu'] = 'staff';
        $data['staffList'] = Staff::where('s_endingDate', null)
            ->get();

        /** Rendering view for staff List */
        return view('staff.list', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['menu'] = 'staff';
        $data['userRoles'] = UserRole::where('ur_id', '<>', 1)
            ->get();

        /** Rendering view for staff List */
        return view('staff.add', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'name'        => 'required|string',
            'mobile'      => 'required|unique:users,u_mobile',
            'address'     => 'nullable',
            'role'        => 'required|integer',
            'password'    => 'required|min:6',
            'image'       => 'nullable|file|image',
            'salary'      => 'required|numeric|min:0',
            'joiningDate' => 'required'
        ];

        $messages = [
            'name.required'        => 'Please provide Staff Name.',
            'name.string'          => 'Please provide a valid Staff Name.',
            'mobile.required'      => 'Please provide staff\'s mobile no..',
            'mobile.unique'        => 'This mobile number has already used.',
            'password.required'    => 'Please provide a password for the staff.',
            'password.min'         => 'Password must contain minimum 6 characters.',
            'image.file'           => 'Please provide an image file.',
            'image.image'          => 'Please provide an image file.',
            'role.required'        => 'Please select Staff Role',
            'role.integer'         => 'Please select a valid Staff Role',
            'salary.required'      => 'Please provide Staff Salary Amount',
            'salary.numeric'       => 'Please provide a valid Salary Amount.',
            'salary.min'           => 'Salary can\'t be less than 0.',
            'joiningDate.required' => 'Please provide the joining date.'
        ];

        $this
            ->validate($request, $rules, $messages);

        /**
         * Insert into `users`
         */
        $user = new User;

        $user->u_name     = $request->input('name');
        $user->u_mobile   = $request->input('mobile');
        $user->u_password = Hash::make($request->input('password'));
        $user->u_address  = $request->input('address');
        $user->ur_id      = $request->input('role');

        $user->save();

        $user->u_image = '';
        $file = $request->file('image');

        if ($file) {
            $file->store('users');
            $user->u_image = 'storage/app/users/' . $file->hashName();

            $user->save();
        }

        $staff = new Staff;

        $staff->u_id          = $user->u_id;
        $staff->s_salary      = $request->input('salary');
        $staff->s_joiningDate = Carbon::createFromFormat('d/m/Y', $request->input('joiningDate'))
            ->format('Y-m-d');

        $staff->save();

        return back()
            ->with('success', 'A Staff has been added.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/staff/add.blade.php
@extends('layouts.master')

@section('title', 'Add New Staff')

@section('customcss')
    <link href="{{asset('public/assets/vendors/custom/datatables/datatables.bundle.css')}}" rel="stylesheet" type="text/css" />
@endsection

@section('main')
    <div class="m-grid__item m-grid__item--fluid m-wrapper">

        <!-- BEGIN: Subheader -->
        <div class="m-subheader ">
            <div class="d-flex align-items-center">
                <div class="mr-auto">
                    <h3 class="m-subheader__title ">New Staff</h3>
                </div>
            </div>
        </div>

        <div class="m-portlet m-portlet--mobile">

            <!--begin::Form-->
            <form class="m-form m-form--fit m-form--label-align-right"
                  action="{{url('staff')}}"
                  method="post"
                  enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="m-portlet__body">
                    <div class="col-sm-12" style="padding-left: 0;">
                        @if (session('success'))
                            <div class="alert alert-success">
                                {{ session('success') }}
                            </div>
                        @elseif($errors->any())
                            <div class="alert alert-danger">
                                {{ $errors->first() }}
                            </div>
                        @endif
                    </div>

                    <div class="form-group m-form__group">
                        <label for="name">Name</label>
                        <input type="text"
                               class="form-control m-input"
                               id="name" value="{{old('name')}}"
                               name="name"
                               aria-describedby="staffName"
                               placeholder="Enter name">
                        <span class="m-form__help">Staff's Full Name</span>
                    </div>

                    <div class="form-group m-form__group">
                        <label for="mobile">Mobile</label>
                        <input type="text"
                               class="form-control m-input"
                               id="mobile"
                               value="{{old('mobile')}}"
                               name="mobile"
                               aria-describedby="staffMobile"
                               placeholder="Enter Mobile No.">
                        <span class="m-form__help">Staff's Contact Number</span>
                    </div>

                    <div class="form-group m-form__group">
                        <label for="address">Address</label>
                        <textarea class="form-control m-input" id="address" name="address" rows="3" placeholder="Enter Address">{{old('address')}}</textarea>
                    </div>

                    <div class="form-group m-form__group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control m-input" id="password" name="password" placeholder="Choose a password for the staff">
                    </div>

                    <div class="form-group m-form__group">
                        <label for="role">Role</label>
                        <select id="role" name="role" class="form-control m-input">
                            @foreach ($userRoles as $userRole):
                                <option value="{{$userRole->ur_id}}">{{$userRole->ur_name}}</option>
                            @endforeach
                        </select>
                        <span class="m-form__help">Choose Staff Role</span>
                    </div>

                    <div class="form-group m-form__group">
                        <label for="image">Image</label>
                        <input type="file" class="form-control m-input" id="image" name="image" aria-describedby="emailHelp">
                        <span class="m-form__help">Staff's Picture</span>
                    </div>

                    <div class="form-group m-form__group">
                        <label for="salary">Salary</label>
                        <input type="text" class="form-control m-input" id="salary" name="salary" value="{{old('salary')}}" aria-describedby="emailHelp" placeholder="Enter Salary">
                        <span class="m-form__help">Staff's Salary you'll provide</span>
                    </div>

                    <div class="form-group m-form__group">
                        <label for="joiningDate">Joining Date</label>
                        <input type="text" class="form-control m-input" id="joiningDate" name="joiningDate" value="{{old('joiningDate')}}" aria-describedby="emailHelp" placeholder="Enter Staff's joining date">
                        <span class="m-form__help">Staff's Joining Date</span>
                    </div>
                </div>

                <div class="m-portlet__foot m-portlet__foot--fit">
                    <div class="m-form__actions">
                        <button type="submit" class="btn btn-primary">Add Staff</button>
                        <button type="reset" class="btn btn-secondary">Cancel</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('customjs')
    <script src="{{asset('public/assets/vendors/custom/datatables/datatables.bundle.js')}}"></script>
    <script src="{{asset('public/js/staff.js')}}"></script>
@endsection

resources/views/staff/addTransaction.blade.php
@extends('layouts.master')

@section('title', 'Add Salary Transaction')

@section('customcss')
<link href="{{asset('public/assets/vendors/custom/datatables/datatables.bundle.css')}}" rel="stylesheet" type="text/css" />
@endsection

@section('main')
<div class="m-grid__item m-grid__item--fluid m-wrapper">

    <!-- BEGIN: Subheader -->
    <div class="m-subheader ">
        <div class="d-flex align-items-center">
            <div class="mr-auto">
                <h3 class="m-subheader__title ">New Salary transaction</h3>
            </div>
        </div>
    </div>

    <div class="m-portlet m-portlet--mobile">

        <!--begin::Form-->
        <form class="m-form m-form--fit m-form--label-align-right"
              action="{{url('salary-transaction')}}"
              method="post"
              enctype="multipart/form-data">
            {{ csrf_field() }}
            <div class="m-portlet__body">
                <div class="col-sm-12" style="padding-left: 0;">
                    @if (session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                    @elseif($errors->any())
                    <div class="alert alert-danger">
                        {{ $errors->first() }}
                    </div>
                    @endif
                </div>

                <div class="form-group m-form__group">
                    <label for="staff">Staff</label>
                    <select id="staff" name="staff" class="form-control m-input">
                        @foreach ($staffList as $staff):
                        <option value="{{$staff->s_id}}">{{$staff->user->u_name . ' - ' . $staff->user->userRole->ur_name}}</option>
                        @endforeach
                    </select>
                    <span class="m-form__help">Choose Staff</span>
                </div>

                <div class="form-group m-form__group">
                    <label for="salary">Salary Amount</label>
                    <input type="text" class="form-control m-input" id="salary" name="salary" value="{{old('salary')}}" aria-describedby="emailHelp" placeholder="Enter Salary">
                    <span class="m-form__help">Staff's Salary you'll provide</span>
                </div>

                <div class="form-group m-form__group">
                    <label for="month">Select Month</label>
                    <input type="text" class="form-control m-input" id="month" name="month" value="{{old('month')}}" aria-describedby="emailHelp" placeholder="Month of the Salary">
                    <span class="m-form__help">Month of the salary</span>
                </div>
            </div>

            <div class="m-portlet__foot m-portlet__foot--fit">
                <div class="m-form__actions">
                    <button type="submit" class="btn btn-primary">Add</button>
                    <button type="reset" class="btn btn-secondary">Cancel</button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

@section('customjs')
<script src="{{asset('public/assets/vendors/custom/datatables/datatables.bundle.js')}}"></script>
<script src="{{asset('public/js/salary.transaction.js')}}"></script>
@endsection

resources/views/staff/list.blade.php
@extends('layouts.master')

@section('title', 'Staff list')

@section('customcss')
    <link href="{{asset('public/assets/vendors/custom/datatables/datatables.bundle.css')}}" rel="stylesheet" type="text/css" />
@endsection

@section('main')
    <div class="m-grid__item m-grid__item--fluid m-wrapper">

        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Staff List
                        </h3>
                    </div>
                </div>
                <div class="m-portlet__head-tools">
                    <ul class="m-portlet__nav">
                        <li class="m-portlet__nav-item">
                            <a href="{{url('staff/create')}}" class="btn btn-info m-btn m-btn--custom m-btn--icon m-btn--air">
                                <span>
                                    <i class="la la-plus"></i>
                                    <span>Add New Staff</span>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="m-portlet__body">

                <!--begin: Datatable -->
                <table class="table table-striped- table-bordered table-hover table-checkable" id="staffList">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Mobile</th>
                        <th>Address</th>
                        <th class="text-center">Salary</th>
                        <th>Joining Date</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($staffList as $staff)
                        <tr data-id="{{$staff->s_id}}">
                            <td>{{$staff->user->u_name}}</td>
                            <td>{{$staff->user->u_mobile}}</td>
                            <td>{{$staff->user->u_address}}</td>
                            <td class="text-right">{{number_format($staff->s_salary, 2)}}</td>
                            <td>{{$staff->s_joiningDate}}</td>
                            <td>
                                <a href="javascript:void(0)" class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill" title="Details">
                                    <i class="la la-search-plus"></i>
                                </a>

                                <a href="{{url('staff/'. $staff->s_id . '/edit')}}" class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill" title="Edit">
                                    <i class="la la-edit"></i>
                                </a>

                                <a href="javascript:void(0)" class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill" title="Delete" data-toggle="tooltip"><i class="la la-trash"></i></a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('customjs')
    <script src="{{asset('public/assets/vendors/custom/datatables/datatables.bundle.js')}}" type="text/javascript"></script>
    <script src="{{asset('public/js/staff.js')}}" type="text/javascript"></script>
@endsection

resources/views/staff/salaryTransactions.blade.php
@extends('layouts.master')

@section('title', 'Salary Transactions')

@section('customcss')
    <link href="{{asset('public/assets/vendors/custom/datatables/datatables.bundle.css')}}" rel="stylesheet" type="text/css" />
@endsection

@section('main')
    <div class="m-grid__item m-grid__item--fluid m-wrapper">

        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Salary Transactions
                        </h3>
                    </div>
                </div>
                <div class="m-portlet__head-tools">
                    <ul class="m-portlet__nav">
                        <li class="m-portlet__nav-item">
                            <a href="{{url('salary-transaction/create')}}" class="btn btn-info m-btn m-btn--custom m-btn--icon m-btn--air">
                                <span>
                                    <i class="la la-plus"></i>
                                    <span>Add New Transaction</span>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="m-portlet__body">

                <!--begin: Datatable -->
                <table class="table table-striped- table-bordered table-hover table-checkable" id="staffList">
                    <thead>
                    <tr>
                        <th>Staff</th>
                        <th>Role</th>
                        <th class="text-center">Given Salary</th>
                        <th class="text-center">Paid Salary</th>
                        <th class="text-center">Due Salary</th>
                        <th>Owner</th>
                        <th>Month</th>
                        <th>Given Date</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($transactions as $transaction)
                        <tr data-id="{{$transaction->st_id}}">
                            <td>{{$transaction->staff->user->u_name}}</td>
                            <td>{{$transaction->staff->user->userRole->ur_name}}</td>
                            <td class="text-right">{{number_format($transaction->st_givenSalary, 2)}}</td>
                            <td class="text-right">{{number_format($transaction->st_totalPaidSalary, 2)}}</td>
                            <td class="text-right">{{number_format($transaction->st_totalDueSalary, 2)}}</td>
                            <td>{{$transaction->owner->user->u_name}}</td>
                            <td>{{$transaction->st_month}}</td>
                            <td>{{$transaction->created_at}}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('customjs')
    <script src="{{asset('public/assets/vendors/custom/datatables/datatables.bundle.js')}}" type="text/javascript"></script>
    <script src="{{asset('public/js/staff.js')}}" type="text/javascript"></script>
@endsection